version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - DEBUG=true
      - LOG_LEVEL=debug
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://127.0.0.1:3000"]
    volumes:
      - ./backend:/app
      - backend_data:/app/data
      - /app/__pycache__  # Exclude __pycache__ from volume mount
    restart: unless-stopped
    command: ["uvicorn", "main:socket_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - VITE_ENABLE_DEBUG=true
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from volume mount
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  backend_data:
    name: ai_digital_workforce_dev_data